development:
  adapter: postgresql
  encoding: unicode
  database: ajax-check-list-dev
  pool: 5
  timeout: 5000
  username: johnfigueiredo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ajax-check-list-test
  pool: 5
  timeout: 5000
  username: johnfigueiredo
  password:
